server:
  port: 8090

spring:
  application:
    name: msvc-course
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
  config:
    import: "optional:configserver:"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courseDb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
